apiVersion: v1
kind: Service
metadata:
  name: python-jupyter-service
spec:
  type: NodePort
  selector:
    app: python-jupyter-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9999
